text = "Use lambda functions when an anonymous function is required for a short period of time."
print(text.count("a",6,50))
print(text.index("e",6,25))
print(text.find("f",6,25))
print(text.replace("s","x",2))
print(text.startswith("f",11,15))
print(text.endswith("c",11,15))
print(text.upper())
print(text.lower())
print(text.capitalize())
print(text.title())
print(text.center(100,"-"))
print(text.casefold())
a = ["Orange","Lemon","Watermelon"]
print("#".join(a))
print(text.zfill(100))
print(text.swapcase())
print(len(text))
print(text.split(" ",2))
print(text.rsplit(" ",2))
print(text.strip("."))
print(text.lstrip("U"))
print(text.rstrip("."))
print(text.partition("anonymous"))
print(text.rpartition("anonymous"))
print(text.rfind("f",15,87))
print(text.rindex("r",15,87))
print(text.ljust(100,"-"))
print(text.rjust(100,"-"))
text = "Use lambda functions when an anonymous function is required \n for a short period of time."
print(text.splitlines(False))
print(text.isalnum())
print(text.isalpha())
print(text.isdigit())
print(text.isprintable())
print(text.islower())
print(text.isupper())
print(text.istitle())
print(text.isdecimal())
print(text.isnumeric())
print(text.isspace())
print(text.isidentifier())
print(text.isascii())
text = "Hello, World"
x = "ord"
y = "yke"
z = "l,"
print(text.translate(str.maketrans(x,y,z)))
print(text.encode(encoding="ascii",errors='ignore'))
a = "Hello"
b = "World"
print(a + ", " + b)
print(a[::2])
print(a[-3::-1])