set_a = {10,20,30,40,50,10}
print(set_a)
set_b = set([10,20,30,40,50,60,10,20])
print(set_b)
set_b.clear()
print(set_b)
set_a.remove(50)
print(set_a)
set_a.update({60,70,80})
print(set_a)
set_a.discard(80)
print(set_a)
set_c = set_a.copy()
print(set_c)
set_a.add(100)
print(set_b)
set_d = set_a.symmetric_difference(set_c)
print(set_d)
set_a.symmetric_difference_update(set_c)
print(set_a)
set_e = set_c.difference(set_a)
print(set_e)
set_c.difference_update(set_a)
print(set_c)
set_f = set_c.intersection(set_a)
print(set_f)
set_d.intersection_update(set_a)
print(set_d)
set_d.pop()
print(set_d)
print(set_d.isdisjoint(set_a))
print(set_d.issubset(set_a))
print(set_d.issuperset(set_a))
set_g = set_d.union(set_a)
print(set_g)
del set_g